### ISSUE TITLE
 immortal refreshToken if user don't /logout can be more dangerous than you think

### ISSUE THREAD

**Issue by rootz491** [jkasun/stack-abuse-express-jwt#5]
Hey, there's a flow that apparently no-one has noticed yet.
Let say, during login, server is generating authToken and refreshToken and stored refreshToken on database somewhere.

Now acc. to this article, refreshToken can only be removed when user hits /logout endpoint with `refreshToken` in body, right?! What if user do not logout from application, and just closes the browser. Then, refreshToken is still there in database. Right? And as fas as i know, there's no other way to remove that refreshToken. Meaning it will become a refreshToken that never expires. (now when user go to same site later, user have to login coz authToken already expired)

Worst case scenario: suppose there's xss in application using which attacker's able to steal Tokens, and also user did not logout. Now attacker has the Refresh Token that never expires and auth Token, 
He can refresh the auth token with this infinite refreshToken, and will be logged in as victim user forever.

Making request to refresh auth token in every few minutes is not very difficult for hacker, attacker can automate this task easily.

**Comment by black-evil-dragon** [comment]
Hello! 
~
I recently found an article explaining how JWT works (these are its sources). How can this be fixed?

**Comment by rootz491** [comment]
The way i do it nowadays is,
`AuthToken` expires in 15 or 30 mins.
`RefreshToken` expires in 3 or 6 days.

if user returns to website with 3 or 6 days from his last visit, then he dont need to login again, and can just have new refresh token (thru some middleware probably). 
else user have to login as that refresh token has expired as well as auth token ofc!

---

I've been using JWT Auth Flow in almost every project these days.
and surely, there are multiple solutions to this problem. But this one is widely adopted (Google Firebase uses the same)

**Comment by black-evil-dragon** [comment]
Oh okay, I'll take a look at this. Thanks for the advice!)
